### ISSUE TITLE
How to create the alphabit.js

### ISSUE THREAD

**Issue by chethanforever** [robhawkes/google-bouncing-balls#4]
Hi..
I the work you did is awesome....
but i was just wondering about the alphabit.js how did you create the points....????

is there any tools or some things....??? to generate..??

**Comment by robhawkes** [comment]
I didn't create the alphabet, I just used the existing positions from the Google version. You might find this version of the Google balls code more helpful as it uses an entire alphabet: http://dotty-dots.appspot.com/

**Comment by chethanforever** [comment]
I have gone through with the following link... Line No 60
http://dmongeau-petitpas.blogspot.in/2010/09/google-doodle-moving-circles-google.html

But the google version has only positions for GOOGLE only....

In the following link... it contains the positions for all the letters...
http://dotty-dots.appspot.com//static/alphabet.js

How did you create the rest???
Is there any way  to decrease the font by changing positions???

Thanks,
Chethan.M.S

**Comment by robhawkes** [comment]
The dotty-dots version isn't anything to do with me so you'll need to 
contact the guys who created it. :)

chethanforever wrote:
